### ISSUE TITLE
Governance functions description

### ISSUE THREAD

**Issue by benefacto** [AskobarNetwork/Askolend#3]
What will these functions do (as per [white paper](https://askobar-network.com/wp-content/uploads/2020/07/askolend-whitepaper.0.2.0.pdf))?
setBaseRate
setMultiplierM
setMultiplierN
setOptimal

**Comment by carlsbad-sunshine** [comment]
These set the values for the formulas for setting interest rates. They are set by the Dao.
```The interest rates are then set through governance depending on the specific needs of each
asset class. Interest rates are set based on an optimal ratio O with a base rate of B and the
slopes M and N such that:
When U < O, Borrow Rate = B + (U/O) * M
When U >= O, Borrow Rate = B + M + (U-O)/(1-O) * N```

**Comment by benefacto** [comment]
Great, thanks! See [2.2 Interest Rates](https://askobar-network.com/wp-content/uploads/2020/07/askolend-whitepaper.0.2.0.pdf) for full description.
