### ISSUE TITLE
Make site Mobile-Friendly

### ISSUE THREAD

**Issue by rihp** [AskobarNetwork/Askolend#38]

**Comment by benefacto** [comment]
Currently the tables' and the summary's styling is quite off for mobile (example below on Pixel 4 XL).
![screenshot](https://user-images.githubusercontent.com/10215679/93815635-28594400-fc0b-11ea-881a-0c07e24de558.jpg)
The relative positioning of the elements needs to be reworked so more of it is visible on a mobile browser.

**Comment by benefacto** [comment]
Site does look fine when sideways, though this may not be sufficient:
![Screenshot_20200922-110735](https://user-images.githubusercontent.com/10215679/93920456-0ec80300-fcc4-11ea-996f-307b1ad2b406.jpg)
