### ISSUE TITLE
Need clarification on borrowing rules

### ISSUE THREAD

**Issue by benefacto** [AskobarNetwork/Askolend#4]
Last piece is really needing clarification on borrowing rules from multiple pools since an asset supposedly only belongs to one pool: "Half of the borrowed assets must come from the a2 pool while half come from the a1 pool. However, in the case of insolvency, the insolvent loans are first paid from the a2 pool and only after the a2 pool is exhausted is the a1 pool touched. Since borrowers must use both pools, and the a2 pool represents higher risk to lenders, the market under normal conditions will set substantially higher interest rates for the a2 pool than the a1 pool."

**Comment by carlsbad-sunshine** [comment]
Each asset has two pools.
Borrowers must borrow equally from both pools and pay interest accordingly to both pools.
The only case where the pools affect each other is in the case of undercollateralized liquidations, where the value of the loan is lower than the underlying collateral. In that case, the difference is paid by the high risk a2 pool.

**Comment by benefacto** [comment]
> Each asset has two pools.

Does this mean that lenders choose how much of each pool to lend to for every given asset? Or just like borrowers, do they lend equally to both pools?

**Comment by benefacto** [comment]
@carlsbad-sunshine
