### ISSUE TITLE
There needs to be a multiplier to the asset that is being borrowed.

### ISSUE THREAD

**Issue by rihp** [AskobarNetwork/Askolend#5]

**Comment by benefacto** [comment]
@rihp Can you clarify more about what this means?

**Comment by rihp** [comment]
Notes from the Askobar team regarding this `multiplier` feature:
>  It would need to be set - so for borrowing wEth or DAI,theres less volatility risk so the multiplier would be 1. But for a token like ASKO, it could be 2-5 depending.
> Also ideally should be fractional, eg 1.5. Probably best to use Basis Points (x/10000)
